### PR TITLE
fix some sonar issues and make the code clear

### PR DESCRIPTION
**Pull request by gabrielmendws**

### CODE REVIEW

**Review by leandrooliveiramastercard — DISMISSED** [review]
Reviewed

**Review by leandrooliveiramastercard — DISMISSED** [review]
Reviewed.

**Review by leandrooliveiramastercard — APPROVED** [review]
Reviewed

**Review by laumarques — COMMENTED** [review]
Reviewed

**Review by laumarques — APPROVED** [review]
Reviewed

**Review by JeanBritto — APPROVED** [review]

**Pull request merged**
